### ISSUE TITLE
Possibility to add more then one graph

### ISSUE THREAD

**Issue by cstegm** [Mikesch-mp/icingaweb2-module-grafana#12]
Hi,

It would be nice if we have the possibility to add more than one graph to a service (manually via "Add New Grafana Graph"). This could be useful for services with different metric types. 

For example ping4 has: 
- rta = ms 
- pl = %

**Comment by Mikesch-mp** [comment]
Hi,
not really possible. Imagine a check with like 1000+ metrics. this would take ages to load.
But you can always configure your graph in Grafana, in my provided base metrics ping4 shows both (left and right y-axes are used.)

**Comment by cstegm** [comment]
Hi,
thanks for the hint with left and right y-axes!
If  imagine a check with 1000+ metrics -> thats why i would like to add 2 or 3 graphs more to a services to show the relevant 5-6 metrics.

**Comment by Mikesch-mp** [comment]
Just try to generate the  dashboard that fits your needs, for example you can add a host action in icingaweb2 that points to your dashboard based on hostname.  If you need help creating dashboards, i can  help you , but Grafana is really easy to learn :)

**Comment by TheFlyingCorpse** [comment]
Suggestion that might help this: Provide instances, such as using data from the perfdata already available in icingaweb2 as arguments for the graphs. Allow for regex matching here? 

That way you can get per-disk graph with its separate thresholds or otherwise splitting similar instances in separate graphs where the numbers arent easily normalized to percent in the plugin itself.

**Comment by Mikesch-mp** [comment]
Using data from perfdata is a bad idea, because they dont exist all the time (think about script errors, unkown state etc.). But i think i have an idea to make it possible the easy way. I will make the panelID an comma seperated list, so it will show all the graphs configured for the service (but you have to create them still at your own).

**Comment by TheFlyingCorpse** [comment]
Oh, that would be inconvenient. My 700+ servers arent really configured the same way, at least 50 different disksetups, a lot of one off's.

**Comment by cstegm** [comment]
I like the idea of a comma separated list of panelids - it would be awesome if we have this in the next release :)

**Comment by Mikesch-mp** [comment]
It will be in the next release. Iam have just a truckload of work and only spare time for develop at the moment.

**Comment by Mikesch-mp** [comment]
Added multiple panelIds in v1.0.4
