### ISSUE TITLE
repeatable panel issues

### ISSUE THREAD

**Issue by p0ntsNL** [Mikesch-mp/icingaweb2-module-grafana#170]
I seem to have some issues with the repeatable panel.

graphs.ini:
`[interfaces]
dashboard = "icinga2-interfaces"
panelId = "1"
orgId = ""
repeatable = "yes"`

So the grafana portal is looking like this:
![screen shot 2018-07-16 at 10 31 20](https://user-images.githubusercontent.com/25501135/42749272-71b4a9fc-88e3-11e8-8943-f730e258f709.png)

But when I look in icinga, it looks like this:
![screen shot 2018-07-16 at 10 29 38](https://user-images.githubusercontent.com/25501135/42749289-7c37613a-88e3-11e8-928c-c865d55f74d9.png)

The variables are as following:
![screen shot 2018-07-16 at 10 32 14](https://user-images.githubusercontent.com/25501135/42749306-897dfb4c-88e3-11e8-94e1-2b1c3e2b7354.png)

![screen shot 2018-07-16 at 10 32 36](https://user-images.githubusercontent.com/25501135/42749319-94f4ad54-88e3-11e8-9f33-bc62ec6d24ea.png)

So for some reason, it wants to add more panels than there actually are which is crashing grafana on the server.

**Comment by Mikesch-mp** [comment]
Hi,

you need to set how many metrics there, so the script knows how many are there to repeat.
See the `metrics per panel` option.

**Comment by p0nt** [comment]
Hi,

Thanks for your answer.

I made the metrics per panel 6 but still it does not work.

`[interfaces]
dashboard = "icinga2-interfaces"
panelId = "1"
orgId = ""
repeatable = "yes"
nmetrics = "6"`

![screen shot 2018-07-16 at 13 11 57](https://user-images.githubusercontent.com/25501135/42755776-d5218ce2-88f9-11e8-9a1b-49a907291f4b.png)

![screen shot 2018-07-16 at 13 12 07](https://user-images.githubusercontent.com/25501135/42755783-de9cfc7a-88f9-11e8-8316-76a486b5f8e8.png)

![screen shot 2018-07-16 at 13 12 27](https://user-images.githubusercontent.com/25501135/42755800-e77cc320-88f9-11e8-859c-c7af21fdf66a.png)

**Comment by Mikesch-mp** [comment]
Same here, did you configure the panel to repeat in grafana also?

**Comment by p0nt** [comment]
yes in grafana its also in repeat.

![screen shot 2018-07-16 at 14 53 27](https://user-images.githubusercontent.com/25501135/42759654-081a026a-8908-11e8-85c9-5dec1685454f.png)

**Comment by Mikesch-mp** [comment]
Will check my test dashboard later today, there must be something missing in the documentation i wrote

**Comment by p0nt** [comment]
Sure no problem, looking forward to the fix

**Comment by p0nt** [comment]
Hi Mike,

Have you been able to find this?

**Comment by Mikesch-mp** [comment]
I#am under havy workload at the moment, sorry but it will take some days until i will find time.

**Comment by p0nt** [comment]
understandable, let me know when you have something :)

**Comment by Mikesch-mp** [comment]
@p0nt can you please test latest master if it works now for you?

**Comment by jwpit** [comment]
Hi,

i do face a similar problem.
Grafana config looks like this
![image](https://user-images.githubusercontent.com/20476731/52411618-bcc96e00-2adc-11e9-8ab0-64fe093c1ba3.png)

and is working
![image](https://user-images.githubusercontent.com/20476731/52412630-a1ac2d80-2adf-11e9-83a1-a3864d08e0aa.png)

Icinga Config looks like this
![image](https://user-images.githubusercontent.com/20476731/52411652-d5398880-2adc-11e9-9c74-39161d117731.png)

Resulting in displaying 2 instead of 4 expected graphs, whereas the second one is a completely diffenrent panel
![image](https://user-images.githubusercontent.com/20476731/52411762-22b5f580-2add-11e9-85ab-8862107bc231.png)

Setting the metrics to 5 and making all metrics visible shows some other wrong panel instead of the 2nd one but does not change anything else.
Isn't it necessary to set any custom var?

Rgds, Jens

**Comment by Mikesch-mp** [comment]
I wil make a howto video after my holidays,  will be after the Icinga Camp Berlin.

**Comment by jwpit** [comment]
Hi Carsten,
any news about this issue?
Rgds, Jens

**Comment by IsReal8a** [comment]
Hi jwpit,

I worked with this nice module in our brand new monitoring solution with Icinga this week and I "fixed" the problem for my network interfaces (thanks Mike).

The module works like this: You select your service, it gets the panel number defined in your configuration and it will repeat the panel, let's say that I'm using panel 128 as repeatable panel, the repeated panels will be 129, 130, 131, 132,..., n; you get the idea.

The problem is, you have panel 128 (Network Interfaces Traffic) but then you created another panel with the number 131 (Memory), and for example, your panel 128 repeats 50 times because your network check, so, you'll end up without your "repeatable" panel 131, the module will respect the panel 131 you have setup in Grafana and will go for the Memory one, that's why you don't see the correct panels and you see the graphs from other service checks.

You can fix this in two ways:

1. Create your dashboard with all the panels you need and at the end create the panel that will be repeatable. That one will go from 128 to n panels.
2. Create a separate dashboard for that service, in my case, it was easier because I ended up with 300+ panels from my network interfaces.

That leads to another issue that I dirty-fixed and I need to ask a new feature for a real fix :).

Hope this helps.

**Comment by jwpit** [comment]
Thank you IsReal8a,
this explains the behavior.
Until there is a fix, i do opt for 3: don't use checks with a dynamic amount of results.

**Comment by IsReal8a** [comment]
But you'll lose this capability, I suggest to create the dashboard in a way that you'll not require to change it, cheers.
