### ISSUE TITLE
Possibility to change time in the view

### ISSUE THREAD

**Issue by markusr** [Mikesch-mp/icingaweb2-module-grafana#4]
It would be very useful if I could change the view dynamically in the view.

Something similar to here:
https://www.linuxfrickeln.de/content/images/2015/09/icinga2_graphite_demo.png

**Comment by Mikesch-mp** [comment]
Hmm not quite sure if i should add this. For me, and many customers its enough to have a quick graph and then if morre details are needed view it in Grafana. But i will keep it in mind and when someone else request it, i will do it.

**Comment by sysadmama** [comment]
+1 from my side. :-)

**Comment by mattg-92** [comment]
+1 for this

**Comment by xenuser** [comment]
+1. I just had to patch this module because someone required to have 5 graphs for services, each of them with different time intervals (e.g. last hour, last day, last week, last month, last year..).

This requirement becomes more and more common. In my specific case, the owner of the Icingaweb2 installation does not allow all users to have access to Grafana, which is why they only have the graphs which are displayed within Icingaweb2.

**Comment by Mikesch-mp** [comment]
Added with release v1.0.9

**Comment by markusr** [comment]
@Mikesch-mp Thank you for implementing this. I just tested this new feature and it works nicely.
