### ISSUE TITLE
Only timeperiods being displayed

### ISSUE THREAD

**Issue by va1entin** [Mikesch-mp/icingaweb2-module-grafana#44]
Hello,

firstly I have no experience with Grafana or Graphite, only wanted graphs in Icinga2. So I have setup the module according to the guide and Grafana/Graphite with Docker. However I do not get any graphs in the web frontend. I only get a line with timeperiods below the plugin output:

5 minutes : 15 minutes : 30 minutes : 1 hour : 3 hours : 6 hours : 8 hours : 12 hours : 24 hours : 2 days : 7 days : 30 days : 60 days : 6 months : 1 year : 2 years

Also I could not really understand where the data for the graphs comes from in the guide. From my understanding the data of the plugins (for example load values) would have to be put into graphite first somehow, wouldnt it?

Sorry if this is a dumb question and you just have to be a Graphite/Grafana pro to use this module.

Kind regards

**Comment by Mikesch-mp** [comment]
Hi,

i guess you configured proxy mode? If yes please increase the timeout value to 10 or more seconds.

Data comes from Graphite or InlfuxDB, depends what you have installed and configured on your system/Icinga2 installation. 

Regards,

Carsten

**Comment by dnsmichi** [comment]
Please explain how you've configured Icinga 2 to write metrics using the the Graphite feature.

**Comment by mkmcconnell** [comment]
Hi, I'm also somewhat new to Icinga2 and Grafana and I have a similar issue (I think). The main difference is that I see a 'Host Alive' graph instead of an X-Y data chart:

<img width="612" alt="screen shot 2017-05-22 at 6 37 18 pm" src="https://cloud.githubusercontent.com/assets/17187890/26335062/41c89286-3f1e-11e7-8809-5cde58705b3c.png">

I'm using the 'direct' Grafana access method:

<img width="428" alt="screen shot 2017-05-22 at 6 46 31 pm" src="https://cloud.githubusercontent.com/assets/17187890/26335190/16db5b2a-3f1f-11e7-9e4f-2b3a0a287246.png">

Here is the output of 'icinga2 feature list':
_Disabled features: compatlog debuglog livestatus opentsdb statusdata
Enabled features: api checker command gelf graphite ido-mysql influxdb mainlog notification perfdata syslog_

(Both Icinga2 and Grafana are on the same Ubuntu 16.04 Linux host)

Any help would be greatly appreciated!

- Michael

**Comment by Mikesch-mp** [comment]
Hi Michael,

i assume you imported the 2 dashboards into Grafana and choosed the right data-source.
Did you configure the Hostalive graph in the module? Host checks are treated like service checks, you have to configure them and they dont work with the icinga2-default dashboard.

![image](https://cloud.githubusercontent.com/assets/6574967/26350921/821e4bfe-3fb5-11e7-8410-f37fbe8c08dd.png)

**Comment by Mikesch-mp** [comment]
@mkmcconnell did you solve your problem?
