### ISSUE TITLE
Graph per metric

### ISSUE THREAD

**Issue by sergeygolubev** [Mikesch-mp/icingaweb2-module-grafana#96]
Hello

i have issue with service check with two and more metrics to draw in graph, like "In" and "Out" traffic on interface or multiple interfaces inside one service check.

is there way to implement this task?

**Comment by sergeygolubev** [comment]
https://image.ibb.co/n7iA1v/multiple_metrics.png

**Comment by ramonion** [comment]
you can use this json code for your icinga2-default dashboard:
[icinga2-default-mult-metric.json.txt](https://github.com/Mikesch-mp/icingaweb2-module-grafana/files/1287826/icinga2-default-mult-metric.json.txt)

**Comment by JamboArs** [comment]
Two or more  separate graph lines plotted on the same graph ( in order to Display the  usage of Hard Disc)

Hi, we are monitoring our different Server  with different partions of Hard Disc. I am using ICINGA2 with Grafana. 
 

the Server HARD DISC are  not identical to one another, all do have different Part ions
What do I have to do in order to have two separate graph lines plotted on the same graph based on the values my template variable receives? so that it can show the diffent partions !. Any help I will be much appreciated.

**Comment by Mikesch-mp** [comment]
Hi,

in your panel just change the query and under "GROUP BY" add "tag(metric).
To correct the legend names, add "$tag_metric" in "ALIAS BY".

![image](https://user-images.githubusercontent.com/6574967/31013444-67d5c72e-a516-11e7-842e-d8e8043cae16.png)

**Comment by JamboArs** [comment]
Many Thanks,

 

 I'll try and let you know on WED

 

 enjyo your holiday

 

Rgds

 

 

 

Ramesh

 

Gesendet: Freitag, 29. September 2017 um 13:02 Uhr
Von: Carsten <notifications@github.com>
An: Mikesch-mp/icingaweb2-module-grafana <icingaweb2-module-grafana@noreply.github.com>
Cc: JamboArs <rfzbhana@web.de>, Comment <comment@noreply.github.com>
Betreff: Re: [Mikesch-mp/icingaweb2-module-grafana] Graph per metric (#96)


Hi,

in your panel just change the query and under "GROUP BY" add "tag(metric).
To correct the legend names, add "$tag_metric" in "ALIAS BY".

**Comment by TheBigfoot** [comment]
Is there a way to set this with Graphite datasource as well? These settings are not available for graphiteDS.
